<?php
echo "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'>\n";
echo "<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='fr'>\n";

echo "<html>";
echo "<head>\n";

//Feuille de style
$css = URL."/css/carte.css";
echo "<link rel='stylesheet' type='text/css' href='".$css."'>\n\n";

echo "<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1' />\n";
echo "</head>\n";
echo "<body>\n\n";
	
echo "<input id='code' type='hidden' value='".$this->carte["proprietes"]["zz_ca_code"]."'/>\n\n";

echo "<span id='titre'></span>\n\n";

echo "<div id='legende'></div>\n\n";

echo "<div id='map' class='map' style= 'width:100%; height:100%'></div>\n\n";

echo "</body>\n\n";

echo "<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?sensor=false'></script>\n";
echo "<script type='text/javascript' src='".URL."/js/classes/Objet.js'></script>\n";
echo "<script type='text/javascript' src='".URL."/js/classes/Carte.js'></script>\n";
echo "<script type='text/javascript' src='".URL."/js/scripts/carte.js'></script>\n";
echo "</html>";
?>